import { redirect } from 'next/navigation'
import { db } from '@/lib/db'
import { requireUserId } from '@/lib/session'
import { getProfileWithMetrics } from '@/lib/profile'
import { dayRange } from '@/lib/foodLog'
import { scaleMacros, sumMacros } from '@/lib/nutrition'
import { isAiEnabled } from '@/lib/ai/client'
import { MEAL_SLOTS, type MealSlot } from '@/lib/types'
import MealCard from '@/components/MealCard'
import GeneratePlanButton from '@/components/GeneratePlanButton'

const LABEL: Record<MealSlot, string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  snack: 'Snacks',
  dinner: 'Dinner',
}

export default async function DietPage() {
  const userId = await requireUserId()
  const result = await getProfileWithMetrics(userId)
  if (!result) redirect('/onboarding')

  const { start, end } = dayRange(new Date())
  const plan = await db.mealPlan.findFirst({
    where: { userId, date: { gte: start, lt: end } },
    orderBy: { generatedAt: 'desc' },
    include: { items: { include: { food: true }, orderBy: { id: 'asc' } } },
  })

  const totals = plan ? sumMacros(plan.items.map((i) => scaleMacros(i.food, i.servings))) : null
  const { calorieTarget, proteinTarget } = result.metrics

  return (
    <main className="mx-auto flex max-w-2xl flex-col gap-4 p-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">Today&apos;s diet plan</h1>
          <p className="mt-1 text-sm text-gray-600">
            Target {calorieTarget} kcal · {proteinTarget} g protein
          </p>
        </div>
        <GeneratePlanButton hasPlan={Boolean(plan)} />
      </div>

      {!isAiEnabled() && (
        <p className="rounded-lg bg-blue-50 p-3 text-xs text-blue-900">
          No AI key configured, so plans are generated by the built-in planner. Add{' '}
          <code>GEMINI_API_KEY</code> to <code>.env</code> for AI-written plans with explanations.
        </p>
      )}

      {!plan ? (
        <p className="rounded-lg border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">
          No plan yet. Generate one to get started.
        </p>
      ) : (
        <>
          <div className="rounded-lg bg-gray-50 p-3 text-sm">
            <strong>{Math.round(totals!.kcal)} kcal</strong> · {Math.round(totals!.proteinG)} g
            protein · {Math.round(totals!.carbsG)} g carbs · {Math.round(totals!.fatG)} g fat
            <span className="ml-2 text-xs text-gray-500">
              ({plan.source === 'ai' ? 'AI generated' : 'generated offline'})
            </span>
          </div>

          {MEAL_SLOTS.map((slot) => (
            <MealCard
              key={slot}
              slot={slot}
              label={LABEL[slot]}
              items={plan.items.filter((i) => i.mealSlot === slot)}
            />
          ))}
        </>
      )}
    </main>
  )
}
